- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: false
    update_cache: true
    cache_valid_time: 86400 # One day
  become: true

- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
  when: ansible_os_family == 'Debian'
  become: true

- name: Reset ufw
  community.general.ufw:
    state: reset
  become: true

- name: Enable UFW and close all ports
  community.general.ufw:
    state: "{{ 'enabled' if (ufw_enabled | default(true)) else 'disabled' }}"
    policy: deny
  become: true

- name: Allow specific ports
  community.general.ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  loop: "{{ ufw_rules }}"
  when: ufw_rules is defined

- name: Start ufw service status
  ansible.builtin.systemd:
    name: ufw
    state: "{{ 'started' if (ufw_enabled | default(true)) else 'stopped' }}"
    enabled: "{{ ufw_enabled | default(true) }}"

- name: Reload ufw
  community.general.ufw:
    state: reloaded
  when: ufw_enabled | bool
